### ISSUE TITLE
product listing as columns: image resizing

### ISSUE THREAD

**Issue by torvista** [lat9/ZCA-Bootstrap-Template#268] opened 2023-07-24 14:36 UTC
Vanilla site.
Shortcut
UPDATE configuration SET configuration_value=0 WHERE configuration_key="PRODUCT_LISTING_COLUMNS_PER_ROW";
Result before page threshold:
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/4391026/feee7547-63a3-4112-b2d6-2377572f02d5)

Is it possible to get the images to resize in their frame/keep their relative size?

**Comment by torvista** [comment] 2023-08-10 10:46
Other examples I've seen have product listings maintain the frame (and image size) fixed as the window resizes/having the surrounding space resizing, until passing a breakpoint.
eg:https://bootsnipp.com/snippets/N6yNO

**Comment by lat9** [comment] 2023-08-10 13:56
By `vanilla`, I'm presuming that you mean without Image Handler.  Please verify.

**Comment by torvista** [comment] 2023-08-10 14:31
Yes, only add-on is Bootstrap template.

**Comment by lat9** [comment] 2023-08-11 00:36
I'm not seeing that wonky image display (having disabled IH on my test site):
![image](https://github.com/lat9/ZCA-Bootstrap-Template/assets/2685585/126fef2b-a7e1-4ace-ad36-4c746056bb1e)

What are your Bootstrap configuration settings for Left/Center/Right column-widths and the Images configuration settings for Small Image Width/Height?

**Comment by dbltoe** [comment] 2023-08-11 02:03
you had mentioned using code, did you go to admin >>  Configuration >> Product Listing and see for sure that Columns Per Row was in fact set to 0?  Just a WAG

**Comment by torvista** [comment] 2023-08-11 09:03
Columns Per Row = 0

Finally, I find the offending option is having
IMAGE_PRODUCT_LISTING_WIDTH set to 200
The height as 80/100 nothing has no effect.

**Comment by lat9** [comment] 2024-04-26 15:15
Crud, this is pretty much a duplicate of #359.  Since I've pushed code to that issue, I'll be closing this one as a duplicate.

**Comment by proseLA** [comment] 2024-09-05 13:54
ok, this issue is not a duplicate of #359.  it is something different.  specifically, it is caused by this code:

https://github.com/lat9/ZCA-Bootstrap-Template/blob/aca0f0046d22d2875a9622fb1ece03de6453c597/includes/templates/bootstrap/css/stylesheet_zca_colors.php#L371-L373

here we are specifying a minimum width for the image that could be greater than the computed width of the card.

curiously enough, on @lat9's site, she has overridden that as seen here:

![image](https://github.com/user-attachments/assets/4ed09b64-cb2e-49c1-8daa-c164a2993858)

i have found that changing the code to be either:

```
min-width: auto;
// or
min-width: 100%;
```
provides better results; although each has it's own quirks based on the image size being used.

**Comment by lat9** [comment] 2024-09-05 15:17
Re-opening for investigation.

**Comment by lat9** [comment] 2024-09-05 15:20
FWIW, that min-width update was added via [this](https://github.com/lat9/ZCA-Bootstrap-Template/commit/e2c0c59623c924ef97921fdcd8691496feffdb8b) commit in 2020.

**Comment by proseLA** [comment] 2024-09-05 15:25
> FWIW, that min-width update was added via [this](https://github.com/lat9/ZCA-Bootstrap-Template/commit/e2c0c59623c924ef97921fdcd8691496feffdb8b) commit in 2020.

we all mistakes make... myself included...

**Comment by lat9** [comment] 2024-09-05 15:26
Does that styling change posted above "do the trick"?

**Comment by lat9** [comment] 2024-09-05 15:27
> > FWIW, that min-width update was added via [this](https://github.com/lat9/ZCA-Bootstrap-Template/commit/e2c0c59623c924ef97921fdcd8691496feffdb8b) commit in 2020.
> 
> we all mistakes make... myself included...

Yep, I was just tracing back to see the "how-come-for" that was added.

**Comment by proseLA** [comment] 2024-09-05 15:35
> Perhaps removing that min-width from this file and adding
> 
> ```
> .listingProductImage {
>     max-height: 100%;
>     max-width: 100%;
> }
> ```

yes that also works... 

i am not sure which is the best way; as i am not the css king...

**Comment by lat9** [comment] 2024-09-05 15:56
FWIW, I've found that simply removing that styling from the file and letting the base Bootstrap take over appears to correct the issue.

I've created a test product with a 1231 x 923 base image and have configured Product Listing Image Width/Height to each be 300.

The image overflows as-is:
![image](https://github.com/user-attachments/assets/e1a958d1-e8d9-40e1-b9fb-324bfe5fcc0c)

... but displays "in bounds" just removing that styling:
![image](https://github.com/user-attachments/assets/057f7ead-adba-4707-9ba0-f44658594781)

**Comment by proseLA** [comment] 2024-09-05 16:42
FWIW, thanks to @torvista for documenting this issue; thanks to @lat9 for acknowledging & addressing this issue (as well as maintaining this template); thanks to @proseLA for figuring out what the problem is; and thanks to the zen-cart team for making a shopping cart available as open-source.  everyone else who financially benefits from this work should consider who  makes it happen.

TIS.

**Closed** 2024-10-14 15:42 UTC
Labels: bug, fix provided
